version: "3.9"

services:
  web:
    build: .
    ports:
      - "9000:80"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: your_db_user
      DB_PASS: your_db_password
      DB_NAME: todo
    networks:
      - my-network

  db:
    image: mysql:latest  # Use the official MySQL image
    environment:
      MYSQL_ROOT_PASSWORD: your_root_password
      MYSQL_DATABASE: todo
      MYSQL_USER: your_db_user
      MYSQL_PASSWORD: your_db_password
    volumes:
      - db_data:/var/lib/mysql  # Persist data (important!)
    networks:
      - my-network

volumes:
  db_data:

networks:
  my-network: